name: user_repository

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.16.1
  flutter_secure_storage: ^3.3.3
  equatable: ^1.2.0
  cloud_firestore: ^0.13.6
  firebase_core: ^0.4.5